title: Ocelot and ElementaryJS
description: An IDE for JavaScript, without the "bad parts".
theme: jekyll-theme-cayman
github:
  repository_url: https://github.com/ocelot-ide/Ocelot
deployment_url: https://code.ocelot-ide.org
