title: Ocelot and ElementaryJS
description: JavaScript without the "bad parts".
theme: jekyll-theme-cayman
github:
  repository_url: https://github.com/ocelot-ide/Ocelot
deployment_url: https://220.ocelot-ide.org
