name: Build Node project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Select Node 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Backend dependencies
      run: npm ci
      working-directory: backend
    - name: Backend build
      run: npm run-script build
      working-directory: backend
    - name: Frontend dependencies
      run: npm ci
      working-directory: frontend
    - name: Frontend build
      run: npm run-script build
      working-directory: frontend
